### ISSUE TITLE
pics issue

### ISSUE THREAD

**Issue by benante** [CnnJu/artistwebsite#23]
One pic has the JPG extension in capital letter, hence it doesn t show.
Also the image.container img shouldnt have margins, that is the reason why when on mobile only the img in the center doesn't shrink

**Comment by CnnJu** [comment]
ghee that's what that was. i kept looking in my folder on my computer and didn't understand as it looked the same. 
So if I change the names on my computer folder, it doesn't push it here? 
you have to change the file names on github then? 

thanks, it's all done, and ive linked the menu items to the parts of the website

**Comment by benante** [comment]
once you change the names or extension of the files, then you have to push it. "Pushing" basically mean "update the remote project with the one on my local computer " in this case

**Comment by CnnJu** [comment]
Yeah but I have been doing all that and thzn it wasn't updated, I must be pushing wrong
